tinyMCE.addI18n("en.chat_dlg", {
	title: "Insert chat",
	general: "General",
	sound: "Sound",
	enabled: "Enabled",
	disabled: "Disabled",
	show_time: "Show time",
	show_date: "Show date",
	dimensions: "Dimensions",
	background: "Background",
	date: "Date",
	name: "Name",
	moderator_name: "Moderator Name",
	text: "Text",
	avatar: "Avatar",
	yes: "Yes",
	no: "No",
	emoticons: "Emoticons",
	font: "Font",
	font_size: "Font size",
	colors: "Colors",
	fonts: "Fonts",
	creation: "Log creation",
	display: "Log display",
	appearance: "Appearance",
	logs: "Logs",
	authentication: "Authentication",
	login_options: "Login options",
	current_user: "Current user",
	network_user: "Network user",
	public_user: "Public user",
	facebook: "Facebook",
	twitter: "Twitter",
	moderator_roles: "Moderator roles"
});

